stage: "development"
account: 441772730001

envs:

image:
  tag: ""
  repository: ""
  pullPolicy: Always

deployment:
  progressDeadlineSeconds: 30
  targetCPUUtilizationPercentage: 50
  containerName: "kafka-logger-service"
  replicas: 1
  maxReplicas: 1
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  ports:
  selectors:
    - key: app
      value: "kafka-logger-service"
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  hostAliases:
